Bump bamarni/symfony-console-autocomplete from 1.5.4 to 1.5.5
Hand-picked update of the package itself only as the PR from Dependabot
broke CI (CI #231, PR #1269, d8c239ec).

    $ composer --version
    Composer version 2.5.1 2022-12-22 15:33:54
    $ composer update bamarni/symfony-console-autocomplete
    ...

Every phpunit test in the Code Coverage Job gave:

> Exception: Serialization of 'Closure' is not allowed

First assumption was a dependency update caused it, reviewed the
following but could not spot anything Closure related:

- symfony/polyfill-mbstring - v1.26.0 -> v1.27.0 [1]
- symfony/polyfill-php80 - v1.25.0 -> v1.27.0 [2]
- symfony/process - v4.4.41 -> v4.4.44 [3]

Changes are looking pretty maintenance only, but no formal checks, just
eyeballs.

[1]: https://github.com/symfony/polyfill-mbstring/compare/v1.26.0...v1.27.0
[2]: https://github.com/symfony/polyfill-php80/compare/v1.25.0...v1.27.0
[3]: https://github.com/symfony/process/compare/v4.4.41...v4.4.44